name: task_managing_application
description: An application which provides a friendly and convenient way for task management in mobile devices.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  flow_builder: ^0.0.9
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  uuid: ^4.0.0
  async: ^2.11.0
  firebase_storage: ^11.2.6
  badges: ^3.1.2
  avatar_stack: ^1.2.0
  intl: ^0.18.1
  flutter_switch: ^0.3.2
  path_provider: ^2.1.1
  dio: ^5.3.2
  external_path: ^1.0.3
  permission_handler: ^10.4.3
  file_picker: ^5.5.0
  bloc: ^8.1.2
  meta: ^1.9.1
  cached_network_image: ^3.2.3
  pdf: ^3.10.4
  open_file: ^3.3.2
  flutter_pdfview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/avt.svg
    - assets/images/avt.jpg
    - assets/fonts/Montserrat/Montserrat-Regular.ttf
    - assets/fonts/Montserrat/Montserrat-Bold.ttf
    - assets/fonts/Montserrat/Montserrat-Italic.ttf
    - assets/fonts/Montserrat/Montserrat-BoldItalic.ttf


    
  fonts:
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - asset: assets/fonts/Roboto/Roboto-Medium.ttf
      weight: 500
    - asset: assets/fonts/Roboto/Roboto-Bold.ttf
      weight: 700
  - family: Nunito
    fonts:
    - asset: assets/fonts/Nunito/Nunito-Regular.ttf
    - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Nunito/Nunito-Bold.ttf
      weight: 700
  - family: RobotoMono
    fonts:
    - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
    - asset: assets/fonts/Roboto_Mono/RobotoMono-Medium.ttf
      weight: 500
    - asset: assets/fonts/Roboto_Mono/RobotoMono-Bold.ttf
      weight: 700
  - family: IBMPlexSans
    fonts:
    - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
    - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Medium.ttf
      weight: 500
    - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf
      weight: 700
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
      weight: 500
    - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
      weight: 700
  - family: SFProDisplay
    fonts:
    - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Regular.otf
    - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Medium.otf
      weight: 500
    - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Bold.otf
      weight: 700