name: task_managing_application
description: An application which provides a friendly and convenient way for task management in mobile devices.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flow_builder: ^0.0.9
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # assets:
    
  fonts:
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
    - asset: fonts/Roboto-Medium.ttf
      weight: 500
    - asset: fonts/Roboto-Bold.ttf
      weight: 700
  - family: Nunito
    fonts:
    - asset: fonts/Nunito-Regular.ttf
    - asset: fonts/Nunito-SemiBold.ttf
      weight: 600
    - asset: fonts/Nunito-Bold.ttf
      weight: 700
  - family: RobotoMono
    fonts:
    - asset: fonts/RobotoMono-Regular.ttf
    - asset: fonts/RobotoMono-Medium.ttf
      weight: 500
    - asset: fonts/RobotoMono-Bold.ttf
      weight: 700
  - family: IBMPlexSans
    fonts:
    - asset: fonts/IBMPlexSans-Regular.ttf
    - asset: fonts/IBMPlexSans-Medium.ttf
      weight: 500
    - asset: fonts/IBMPlexSans-Bold.ttf
      weight: 700
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
    - asset: fonts/Montserrat-Medium.ttf
      weight: 500
    - asset: fonts/Montserrat-Bold.ttf
      weight: 700