// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpdzMwgA4NdV3fnTzIGqMFE_Jr2nEdzzM',
    appId: '1:165011018642:web:cf7a74ee1fcb10db0c674b',
    messagingSenderId: '165011018642',
    projectId: 'cs426fp',
    authDomain: 'cs426fp.firebaseapp.com',
    storageBucket: 'cs426fp.appspot.com',
    measurementId: 'G-BWC4K6QK8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEaMNAw-XHRtauT3VBNVDqF9_agBGRRFs',
    appId: '1:165011018642:android:5e40b3b14d2258350c674b',
    messagingSenderId: '165011018642',
    projectId: 'cs426fp',
    storageBucket: 'cs426fp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyPuhCjUNfN8bEL9RSOEnU7v9LNu-MyZs',
    appId: '1:165011018642:ios:e5bd2aa037878f540c674b',
    messagingSenderId: '165011018642',
    projectId: 'cs426fp',
    storageBucket: 'cs426fp.appspot.com',
    iosClientId: '165011018642-9ts36i93d0j6idqqa552gsqhe3pehe90.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyPuhCjUNfN8bEL9RSOEnU7v9LNu-MyZs',
    appId: '1:165011018642:ios:3e587418f97d3acd0c674b',
    messagingSenderId: '165011018642',
    projectId: 'cs426fp',
    storageBucket: 'cs426fp.appspot.com',
    iosClientId: '165011018642-766krclobrnkhe2ad6sl422ijlecc34l.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagingApplication.RunnerTests',
  );
}
